TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5

  #The rotational velocity allowed for the base in radians/sec
  max_vel_theta: 10.0
  min_vel_theta: -10.0

  #The minimum rotational velocity allowed for the base while performing in-place rotations in radians/sec
  min_in_place_vel_theta: 1.0

  #Speed used for driving during escapes in meters/sec. Must be negative
  escape_vel: -0.3

  #The x acceleration limit in m/s^2
  acc_lim_theta: 100.0
  acc_lim_x: 10.0
  acc_lim_y: 10.0

  #The weighting for how much the controller should stay close to the path it was given
  pdist_scale: 1.5
  # The weighting for how much the controller should attempt to avoid obstacles
  occdist_scale: 0.15
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  gdist_scale: 0.6


  prune_plan: true

  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.1

  holonomic_robot: false

  meter_scoring: true
