TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.2
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  escape_vel: -0.3
  max_rotational_vel: 0.2
  min_in_place_rotational_vel: 0.05
  min_in_place_vel_theta: 0.05
  holonomic_robot: false
  acc_lim_th: 2.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.08