obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.48, -0.33], [0.48, 0.33], [-0.48, 0.33],  [-0.48, -0.33]]
inflation_radius: 0.2

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}

